/* Lab Bench knowledge base: original definitions grouped by objective. Content: CC BY-SA 4.0.
   Each group generates questions both ways (definition -> term, term -> definition) with distractors from the same group. */

"use strict";
const TERM_GROUPS = [
{obj:"1.1", name:"OSI layers", items:[
 ["Layer 1 (Physical)","Moves raw bits as electrical, light or radio signals; cables, connectors, hubs and repeaters live here"],
 ["Layer 2 (Data link)","Frames and MAC addressing on the local segment; switches and bridges forward here"],
 ["Layer 3 (Network)","Logical addressing and path selection between networks; IP addresses and routers"],
 ["Layer 4 (Transport)","End-to-end delivery using segments or datagrams, port numbers, and TCP reliability"],
 ["Layer 5 (Session)","Sets up, maintains and tears down dialogs between applications"],
 ["Layer 6 (Presentation)","Formats, encodes, compresses and encrypts data so applications can read it"],
 ["Layer 7 (Application)","Network services that applications use directly, such as HTTP, DNS and SMTP"]]},
{obj:"1.1", name:"PDUs", items:[["Bits","Protocol data unit at the physical layer"],["Frame","Protocol data unit at the data link layer"],["Packet","Protocol data unit at the network layer"],["Segment","Protocol data unit for TCP at the transport layer"],["Datagram","Protocol data unit for UDP at the transport layer"]]},
{obj:"1.2", name:"Appliances", items:[
 ["Router","Forwards packets between different IP networks using a routing table"],
 ["Switch","Forwards frames within a LAN using a MAC address table"],
 ["Firewall","Permits or denies traffic between zones based on rules"],
 ["IDS","Monitors traffic and alerts on suspicious activity without blocking it"],
 ["IPS","Sits inline and actively blocks traffic that matches attack signatures"],
 ["Load balancer","Distributes client requests across a pool of servers"],
 ["Proxy server","Makes requests on behalf of clients, often caching and filtering content"],
 ["NAS","File-level storage appliance shared over the network with SMB or NFS"],
 ["SAN","Dedicated high-speed network providing block-level storage, often over Fibre Channel or iSCSI"],
 ["Wireless LAN controller","Centrally configures and manages lightweight access points"],
 ["Access point","Bridges wireless clients onto the wired network"]]},
{obj:"1.2", name:"Applications and functions", items:[
 ["CDN","Geographically distributed servers that cache content close to users"],
 ["VPN","Encrypted tunnel across an untrusted network such as the internet"],
 ["QoS","Prioritizes latency-sensitive traffic such as voice over bulk traffic"],
 ["TTL","Hop counter in an IP packet that is decremented by each router to prevent endless loops"]]},
{obj:"1.3", name:"Cloud networking", items:[
 ["NFV","Runs network functions such as routers and firewalls as software on standard servers"],
 ["VPC","Logically isolated private network inside a public cloud"],
 ["Network security group","Stateful allow rules applied to cloud instances or interfaces"],
 ["Network security list","Subnet-level cloud rules, often stateless, that filter traffic in and out"],
 ["Internet gateway","Lets resources with public IPs in a VPC communicate with the internet"],
 ["NAT gateway","Lets private-subnet cloud resources reach the internet without accepting inbound connections"],
 ["Direct Connect","Dedicated private circuit between an on-premises network and a cloud provider"],
 ["Site-to-site VPN to the cloud","Encrypted tunnel over the internet linking an on-premises network to a VPC"]]},
{obj:"1.3", name:"Cloud models", items:[
 ["Public cloud","Infrastructure owned by a provider and shared by many customers"],
 ["Private cloud","Cloud infrastructure dedicated to a single organization"],
 ["Hybrid cloud","Combines on-premises or private resources with public cloud services"],
 ["SaaS","Provider delivers a complete application; the customer only uses it"],
 ["PaaS","Provider manages the platform and runtime; the customer deploys code"],
 ["IaaS","Provider supplies virtual servers, storage and networking; the customer manages the OS and up"],
 ["Scalability","Ability to add capacity to handle more load, planned ahead"],
 ["Elasticity","Automatically adding and removing resources as demand changes"],
 ["Multitenancy","Many customers share the same physical infrastructure while staying isolated"]]},
{obj:"1.4", name:"IP protocol types", items:[
 ["ICMP","Carries error and diagnostic messages; used by ping and traceroute"],
 ["TCP","Connection-oriented transport with a three-way handshake and guaranteed, ordered delivery"],
 ["UDP","Connectionless transport with low overhead and no delivery guarantee"],
 ["GRE","Tunneling protocol that encapsulates other protocols, without encryption"],
 ["IPsec AH","Provides integrity and authentication for IP packets but no encryption"],
 ["IPsec ESP","Provides encryption, integrity and authentication for IP packets"],
 ["IKE","Negotiates the keys and security associations used by IPsec"]]},
{obj:"1.4", name:"Traffic types", items:[
 ["Unicast","One sender to one specific receiver"],
 ["Multicast","One sender to a group of interested receivers"],
 ["Anycast","One address shared by several nodes; traffic goes to the nearest one"],
 ["Broadcast","One sender to every host on the local network segment"]]},
{obj:"1.5", name:"Copper and fiber media", items:[
 ["Single-mode fiber","Narrow core with a laser light source for long distances, measured in kilometers"],
 ["Multimode fiber","Wider core using LEDs or VCSELs for shorter runs, typically within a building or campus"],
 ["DAC (twinax)","Short copper cable with transceivers attached, used between switches and servers in a rack"],
 ["Coaxial cable","Copper center conductor with shielding, used for cable internet and older networks"],
 ["Plenum cable","Fire-resistant jacket required in air-handling spaces above ceilings"],
 ["Non-plenum (PVC) cable","Cheaper jacket that can release toxic smoke, not allowed in air-handling spaces"],
 ["Cat 6a","Twisted pair rated for 10 Gbps up to 100 m"],
 ["Cat 8","Twisted pair rated for 25 to 40 Gbps over short data center runs up to 30 m"]]},
{obj:"1.5", name:"Transceivers and connectors", items:[
 ["SFP","Hot-pluggable transceiver commonly used for 1 Gbps links"],
 ["QSFP","Four-lane hot-pluggable transceiver for 40 or 100 Gbps links"],
 ["LC connector","Small push-pull fiber connector common on SFPs"],
 ["SC connector","Square push-pull fiber connector"],
 ["ST connector","Round bayonet-style fiber connector that twists to lock"],
 ["MPO connector","Multi-fiber connector carrying 12 or more fibers in one ferrule"],
 ["RJ11","Small connector used for telephone lines"],
 ["RJ45","8-pin connector used for Ethernet twisted pair"],
 ["F-type","Threaded coaxial connector used for cable modems and TV"],
 ["BNC","Bayonet coaxial connector used with older Ethernet and video equipment"]]},
{obj:"1.5", name:"Wireless media", items:[
 ["802.11a","5 GHz, up to 54 Mbps"],["802.11b","2.4 GHz, up to 11 Mbps"],["802.11g","2.4 GHz, up to 54 Mbps"],
 ["802.11n (Wi-Fi 4)","2.4 and 5 GHz with MIMO, up to about 600 Mbps"],["802.11ac (Wi-Fi 5)","5 GHz only with MU-MIMO and wide channels"],
 ["802.11ax (Wi-Fi 6/6E)","2.4, 5 and 6 GHz with OFDMA for dense environments"],
 ["Cellular","Mobile carrier networks such as 4G LTE and 5G used for WAN backup or remote sites"],
 ["Satellite","WAN link with wide coverage but high latency, especially from geostationary orbit"]]},
{obj:"1.6", name:"Topologies and architectures", items:[
 ["Mesh topology","Every node connects to several or all others for maximum redundancy"],
 ["Star (hub and spoke)","All nodes connect to a central device; a central failure affects everyone"],
 ["Hybrid topology","Combines two or more topology types"],
 ["Point to point","A direct link between exactly two endpoints"],
 ["Spine and leaf","Every leaf switch connects to every spine switch, giving predictable east-west latency in data centers"],
 ["Three-tier model","Core, distribution and access layers in a hierarchical campus design"],
 ["Collapsed core","Combines the core and distribution layers into one layer for smaller networks"],
 ["Access layer","Where end devices connect to the network"],
 ["Distribution layer","Aggregates access switches and applies policy and routing between VLANs"],
 ["Core layer","High-speed backbone that moves traffic between distribution blocks"],
 ["North-south traffic","Traffic entering or leaving the data center"],
 ["East-west traffic","Traffic between servers inside the data center"]]},
{obj:"1.7", name:"Special IPv4 ranges", items:[
 ["APIPA (169.254.0.0/16)","Self-assigned address a host uses when DHCP fails"],
 ["RFC 1918","Private ranges 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16"],
 ["Loopback (127.0.0.0/8)","Addresses that always refer to the local host"],
 ["Class D (224.0.0.0 to 239.255.255.255)","IPv4 multicast range"],
 ["Class E (240.0.0.0 and up)","Reserved experimental range"],
 ["CIDR","Classless notation that writes the mask as a prefix length, such as /26"],
 ["VLSM","Using different mask lengths within one address block to size subnets efficiently"]]},
{obj:"1.8", name:"Modern environments", items:[
 ["SDN","Separates the control plane from the data plane so a controller programs network devices"],
 ["SD-WAN","Centrally managed WAN that steers traffic across any transport by application policy"],
 ["Zero-touch provisioning","New devices pull their configuration automatically when first connected"],
 ["VXLAN","Encapsulates Layer 2 frames in UDP to stretch networks across Layer 3, such as between data centers"],
 ["Zero trust architecture","Never trust by location; authenticate and authorize every request with least privilege"],
 ["SASE","Converges SD-WAN with cloud-delivered security services at the edge"],
 ["SSE","The cloud-delivered security part of SASE: secure web gateway, CASB and zero trust network access"],
 ["Infrastructure as code","Defines infrastructure in version-controlled files that tools apply automatically"],
 ["Configuration drift","Devices gradually departing from their approved baseline configuration"],
 ["Dual stack","Running IPv4 and IPv6 at the same time on the same devices"],
 ["Tunneling (IPv6)","Carrying IPv6 packets inside IPv4 to cross networks that only support IPv4"],
 ["NAT64","Translates between IPv6-only clients and IPv4 servers"]]},
{obj:"2.1", name:"Routing", items:[
 ["Static routing","Routes entered manually by an administrator; no protocol overhead"],
 ["OSPF","Link-state interior routing protocol using cost, areas and Dijkstra's algorithm"],
 ["EIGRP","Cisco advanced distance-vector protocol using a composite metric of bandwidth and delay"],
 ["BGP","Path-vector exterior protocol that routes between autonomous systems on the internet"],
 ["Administrative distance","Trust value used to choose between routes from different sources; lower wins"],
 ["Longest prefix match","The most specific matching route is chosen before anything else"],
 ["Metric","Value a single routing protocol uses to choose its best path"],
 ["PAT (NAT overload)","Many private hosts share one public IP, distinguished by port numbers"],
 ["Static NAT","One private address is mapped permanently to one public address"],
 ["FHRP","Gives hosts a virtual default gateway shared by two or more routers for redundancy"],
 ["Virtual IP (VIP)","Address shared by redundant devices that answers whichever device is active"],
 ["Subinterface","Logical interface on one physical port, often one per VLAN for router-on-a-stick"]]},
{obj:"2.1", name:"Administrative distances", items:[["0","Default administrative distance of a connected route"],["1","Default administrative distance of a static route"],["20","Default administrative distance of eBGP"],["90","Default administrative distance of internal EIGRP"],["110","Default administrative distance of OSPF"],["120","Default administrative distance of RIP"]]},
{obj:"2.2", name:"Switching", items:[
 ["VLAN","Logically separate broadcast domain on a switch"],
 ["SVI","Virtual routed interface for a VLAN on a Layer 3 switch"],
 ["Native VLAN","VLAN whose frames cross an 802.1Q trunk untagged"],
 ["Voice VLAN","Separate tagged VLAN on an access port for IP phone traffic"],
 ["802.1Q","Standard that inserts a VLAN tag into Ethernet frames on trunks"],
 ["Link aggregation (LACP)","Bundles several physical links into one logical link for bandwidth and redundancy"],
 ["Spanning Tree Protocol","Blocks redundant switch paths to prevent Layer 2 loops"],
 ["Root bridge","STP reference switch, elected by the lowest bridge ID (priority, then MAC)"],
 ["Jumbo frames","Ethernet frames with an MTU above 1500 bytes, typically 9000, used for storage"],
 ["MTU","Largest frame payload an interface will send without fragmenting"],
 ["Port mirroring (SPAN)","Copies traffic from one or more ports to a monitoring port"]]},
{obj:"2.2", name:"STP port states", items:[["Blocking","STP state that discards frames to prevent a loop but still hears BPDUs"],["Listening","STP state that processes BPDUs while deciding the topology, no learning yet"],["Learning","STP state that builds the MAC table but doesn't forward yet"],["Forwarding","STP state that sends and receives frames normally"],["Disabled","Port is administratively down and not participating in STP"]]},
{obj:"2.3", name:"Wireless", items:[
 ["Channels 1, 6 and 11","The only non-overlapping 20 MHz channels in 2.4 GHz"],
 ["Channel bonding","Combining adjacent channels into a wider channel for more throughput, at the cost of fewer non-overlapping channels"],
 ["802.11h","Requires DFS and transmit power control in 5 GHz to avoid interfering with radar"],
 ["Band steering","Nudges dual-band clients onto 5 or 6 GHz"],
 ["BSSID","MAC address identifying a single access point radio"],
 ["ESSID","Network name shared by several APs so clients can roam"],
 ["Ad hoc network","Wireless devices connect directly without an access point"],
 ["Infrastructure mode","Clients connect through an access point"],
 ["Mesh network","APs connect to each other wirelessly to extend coverage"],
 ["WPA3-Personal (SAE)","Passphrase security using Simultaneous Authentication of Equals, resistant to offline guessing"],
 ["WPA2/WPA3-Enterprise","Per-user authentication through 802.1X and a RADIUS server"],
 ["Captive portal","Web page that guests must accept or log into before getting access"],
 ["Omnidirectional antenna","Radiates evenly in all horizontal directions for general coverage"],
 ["Directional antenna","Focuses signal in one direction for long point-to-point links"],
 ["Autonomous AP","Configured and managed individually"],
 ["Lightweight AP","Managed by a wireless LAN controller"]]},
{obj:"2.4", name:"Physical installations", items:[
 ["MDF","Main distribution frame where the building's core equipment and carrier connections live"],
 ["IDF","Intermediate distribution frame serving a floor or area, uplinked to the MDF"],
 ["Rack unit (U)","1.75-inch unit of vertical rack space"],
 ["Port-side exhaust/intake","Airflow direction that must match the hot aisle/cold aisle layout"],
 ["Patch panel","Terminates horizontal cabling so ports can be cross-connected with patch cables"],
 ["Fiber distribution panel","Terminates and organizes fiber runs"],
 ["UPS","Battery backup that keeps equipment running through short outages and conditions power"],
 ["PDU","Distributes power to devices in a rack, sometimes with remote monitoring"],
 ["Power load","Total draw of equipment, which must stay within circuit and UPS capacity"],
 ["Humidity control","Too low causes static discharge; too high causes condensation and corrosion"],
 ["Clean-agent fire suppression","Puts out fires without water damage to electronics"]]},
{obj:"3.1", name:"Documentation", items:[
 ["Physical diagram","Shows where devices, racks and cables physically are"],
 ["Logical diagram","Shows how traffic flows: subnets, VLANs and routing"],
 ["Layer 1 diagram","Documents cabling, ports and physical connections"],
 ["Layer 2 diagram","Documents switches, VLANs and trunks"],
 ["Layer 3 diagram","Documents IP subnets, routers and routing"],
 ["Rack diagram","Shows what is mounted in each rack unit"],
 ["IPAM","Tracks and manages IP address assignments, DHCP and DNS"],
 ["SLA","Agreement defining the level of service a provider must deliver, such as uptime"],
 ["Wireless survey/heat map","Measured map of Wi-Fi signal strength across a site"],
 ["Asset inventory","Record of hardware, software, licensing and warranty details"]]},
{obj:"3.1", name:"Life cycle and change management", items:[
 ["End of life (EOL)","Vendor stops selling a product"],
 ["End of support (EOS)","Vendor stops providing patches and support"],
 ["Decommissioning","Securely retiring equipment, including wiping data and updating records"],
 ["Change management","Formal request, review, approval and documentation process before changes"],
 ["Baseline (golden) configuration","Approved standard configuration that devices are compared against"],
 ["Backup configuration","Saved copy of a device's configuration used to restore it"],
 ["Production configuration","The configuration currently running on live devices"]]},
{obj:"3.2", name:"Monitoring", items:[
 ["SNMP trap","Unsolicited alert a device sends to the management station"],
 ["MIB","Database of objects that SNMP can query on a device"],
 ["SNMP community string","Shared plain-text password used by SNMPv1 and v2c"],
 ["SNMPv3","SNMP version adding authentication and encryption"],
 ["Flow data (NetFlow)","Summary records of who talked to whom, how much and on which ports"],
 ["Packet capture","Full copy of packets for detailed protocol analysis"],
 ["Baseline","Normal performance measurements used to spot anomalies"],
 ["Syslog collector","Central server that receives log messages from many devices"],
 ["SIEM","Aggregates and correlates logs to detect security events and alert"],
 ["Port mirroring","Sends a copy of traffic to a monitoring tool"],
 ["Availability monitoring","Checks whether devices and services are up"],
 ["Configuration monitoring","Detects unauthorized or unexpected configuration changes"]]},
{obj:"3.2", name:"Syslog levels", items:[["0 Emergency","Syslog level: system is unusable"],["1 Alert","Syslog level: action must be taken immediately"],["2 Critical","Syslog level: critical conditions"],["3 Error","Syslog level: error conditions"],["4 Warning","Syslog level: warning conditions"],["5 Notice","Syslog level: normal but significant condition"],["6 Informational","Syslog level: informational messages"],["7 Debug","Syslog level: debugging messages"]]},
{obj:"3.3", name:"Disaster recovery", items:[
 ["RPO","Maximum acceptable data loss, measured in time"],
 ["RTO","Maximum acceptable time to restore a service"],
 ["MTTR","Average time to repair a failed component"],
 ["MTBF","Average time a repairable system runs between failures"],
 ["Hot site","Fully equipped with current data, ready almost immediately"],
 ["Warm site","Has equipment and connectivity but needs data restored first"],
 ["Cold site","Space and power only; equipment must be brought in"],
 ["Active-active","All nodes serve traffic at the same time"],
 ["Active-passive","A standby node takes over only when the active node fails"],
 ["Tabletop exercise","Team talks through a disaster scenario without touching systems"],
 ["Validation test","Actually performs recovery steps to prove they work"]]},
{obj:"3.4", name:"DHCP", items:[
 ["DHCP scope","Range of addresses and options a server hands out for a subnet"],
 ["DHCP reservation","Always gives a specific device the same address, based on its MAC"],
 ["DHCP exclusion","Addresses inside a scope that the server will never lease"],
 ["Lease time","How long a client may use an address before renewing"],
 ["DHCP option","Extra setting sent with a lease, such as the default gateway or DNS server"],
 ["DHCP relay (IP helper)","Forwards DHCP broadcasts from one subnet to a server on another"],
 ["SLAAC","IPv6 hosts build their own address from the router's prefix with no DHCP server"],
 ["DORA","Discover, Offer, Request, Acknowledge: the DHCP lease exchange"]]},
{obj:"3.4", name:"DNS records", items:[
 ["A record","Maps a name to an IPv4 address"],["AAAA record","Maps a name to an IPv6 address"],["CNAME record","Alias pointing one name at another name"],
 ["MX record","Identifies the mail server for a domain"],["TXT record","Free text, often used for SPF, DKIM and domain verification"],
 ["NS record","Identifies the authoritative name servers for a zone"],["PTR record","Maps an IP address back to a name in a reverse zone"],["SOA record","Holds a zone's primary server, admin contact and serial number"]]},
{obj:"3.4", name:"DNS and time concepts", items:[
 ["Forward lookup zone","Resolves names to IP addresses"],["Reverse lookup zone","Resolves IP addresses to names"],
 ["Authoritative answer","Response from a server that hosts the zone itself"],["Non-authoritative answer","Response from a server's cache or forwarding, not the zone owner"],
 ["Primary DNS server","Holds the writable copy of a zone"],["Secondary DNS server","Holds a read-only copy received by zone transfer"],
 ["Recursive lookup","Server chases the answer through other servers on the client's behalf"],["Hosts file","Local name-to-address file checked before DNS"],
 ["DNSSEC","Signs DNS records so resolvers can verify they weren't forged"],["DoH / DoT","Encrypts DNS queries inside HTTPS or TLS"],
 ["NTP","Synchronizes clocks over UDP 123"],["PTP","Precision Time Protocol for sub-microsecond synchronization"],["NTS","Adds cryptographic authentication to NTP"]]},
{obj:"3.5", name:"Access and management", items:[
 ["Site-to-site VPN","Permanent tunnel joining two networks through their gateways"],
 ["Client-to-site VPN","Individual remote users connect to the corporate network"],
 ["Clientless VPN","Remote access through a web browser using TLS, with no installed client"],
 ["Split tunnel","Only corporate traffic uses the VPN; internet traffic goes directly"],
 ["Full tunnel","All of the client's traffic goes through the VPN"],
 ["Jump box","Hardened host administrators connect through to reach protected systems"],
 ["Out-of-band management","Managing devices over a separate path such as a console server or cellular modem"],
 ["In-band management","Managing devices over the same network that carries user traffic"],
 ["Console connection","Direct serial connection to a device's console port"]]},
{obj:"4.1", name:"Security concepts", items:[
 ["Confidentiality","Keeping data secret from unauthorized people, mainly through encryption"],
 ["Integrity","Ensuring data isn't altered, mainly through hashing and signatures"],
 ["Availability","Keeping systems accessible, through redundancy and resiliency"],
 ["Risk","Likelihood that a threat exploits a vulnerability, times the impact"],
 ["Vulnerability","Weakness that could be exploited"],["Exploit","Code or technique that takes advantage of a vulnerability"],["Threat","Anything that could cause harm, such as an attacker or disaster"],
 ["Data in transit","Data moving across a network, protected with TLS or IPsec"],["Data at rest","Stored data, protected with disk or database encryption"],
 ["PKI","System of certificate authorities and certificates that binds public keys to identities"],
 ["Self-signed certificate","Certificate not issued by a trusted CA, so clients warn by default"],
 ["Geofencing","Allowing or blocking access based on location"],
 ["Honeypot","Decoy system that attracts and records attackers"],["Honeynet","Network of decoy systems"],
 ["Data locality","Requirement that data stays within certain geographic or legal boundaries"],
 ["PCI DSS","Security standard for organizations that handle payment card data"],
 ["GDPR","EU regulation protecting personal data and privacy"]]},
{obj:"4.1", name:"Identity and access", items:[
 ["MFA","Requires two or more factor types, such as something you know and something you have"],
 ["SSO","One login grants access to many applications"],
 ["RADIUS","AAA protocol over UDP, commonly used for network access and 802.1X"],
 ["TACACS+","Cisco AAA protocol over TCP that separates authentication, authorization and accounting; used for device admin"],
 ["LDAP","Protocol for querying and modifying directory services"],
 ["SAML","XML-based standard for exchanging authentication between an identity provider and service"],
 ["Time-based authentication","Access or one-time codes valid only within certain times"],
 ["Least privilege","Users get only the access their job requires"],
 ["Role-based access control","Permissions assigned to roles, and users assigned to roles"]]},
{obj:"4.2", name:"Attacks", items:[
 ["DDoS","Many compromised systems flood a target to make it unavailable"],
 ["VLAN hopping","Gaining access to another VLAN by switch spoofing or double tagging"],
 ["MAC flooding","Filling a switch's MAC table so it floods traffic out every port"],
 ["ARP poisoning","Corrupting ARP caches so traffic for an IP goes to the attacker's MAC"],
 ["ARP spoofing","Sending forged ARP replies that claim another device's IP address"],
 ["DNS poisoning","Corrupting a DNS server or cache so names resolve to malicious addresses"],
 ["DNS spoofing","Forging DNS responses to redirect a victim"],
 ["Rogue DHCP server","Unauthorized DHCP server handing out bad gateways or DNS"],
 ["Rogue access point","Unauthorized AP connected to the wired network"],
 ["Evil twin","Malicious AP impersonating a legitimate SSID to capture users"],
 ["On-path attack","Attacker secretly relays and possibly alters communication between two parties"],
 ["Phishing","Fraudulent messages that trick people into revealing information or running malware"],
 ["Dumpster diving","Searching trash for sensitive information"],
 ["Shoulder surfing","Watching someone enter passwords or view sensitive data"],
 ["Tailgating","Following an authorized person through a secured door"],
 ["Malware","Malicious software such as viruses, worms, ransomware and trojans"]]},
{obj:"4.3", name:"Defenses", items:[
 ["Port security","Limits which or how many MAC addresses may use a switch port"],
 ["802.1X","Port-based network access control that authenticates devices before granting access"],
 ["MAC filtering","Allows or blocks devices by MAC address, easily bypassed by spoofing"],
 ["NAC","Checks identity and device posture before allowing network access"],
 ["DHCP snooping","Blocks DHCP server messages from untrusted ports and builds a binding table"],
 ["Dynamic ARP Inspection","Drops ARP packets that don't match the DHCP snooping binding table"],
 ["ACL","Ordered permit and deny rules evaluated top-down with an implicit deny"],
 ["URL filtering","Blocks web access by address or category"],
 ["Content filtering","Blocks traffic based on what it contains"],
 ["Screened subnet (DMZ)","Network between the internet and the internal network for public-facing servers"],
 ["Key management","Generating, distributing, rotating and revoking cryptographic keys"],
 ["Device hardening","Disabling unused ports and services and changing default passwords"]]},
{obj:"5.1", name:"Troubleshooting methodology", items:[
 ["Identify the problem","Step 1: gather information, question users, identify symptoms, find what changed, duplicate the problem"],
 ["Establish a theory","Step 2: question the obvious and consider top-down, bottom-up or divide-and-conquer approaches"],
 ["Test the theory","Step 3: confirm the cause, or form a new theory or escalate"],
 ["Establish a plan of action","Step 4: plan the fix and identify its potential effects"],
 ["Implement or escalate","Step 5: apply the fix or hand it to someone who can"],
 ["Verify functionality","Step 6: confirm everything works and add preventive measures"],
 ["Document","Step 7: record findings, actions, outcomes and lessons learned"]]},
{obj:"5.2", name:"Cable and interface issues", items:[
 ["Crosstalk","Signal bleeding between wire pairs, often from untwisted wires at terminations"],
 ["Attenuation","Signal weakening over distance, such as copper runs beyond 100 m"],
 ["Interference (EMI)","Noise from motors, lights or power lines corrupting signals"],
 ["Improper termination","Badly crimped or punched-down connectors causing errors or no link"],
 ["TX/RX transposed","Fiber strands swapped so no light reaches the receiver"],
 ["CRC errors","Frames failing the checksum, usually from cabling problems or a duplex mismatch"],
 ["Runts","Frames smaller than 64 bytes, often from collisions or a duplex mismatch"],
 ["Giants","Frames larger than the MTU, often from MTU mismatches"],
 ["Drops","Frames discarded, usually because buffers are full from congestion"],
 ["Err-disabled","Port shut down automatically by the switch after a violation such as port security"],
 ["Administratively down","Port disabled with the shutdown command"],
 ["Suspended","Port-channel member disabled because of an LACP mismatch"],
 ["PoE budget exceeded","Switch has no more power to give, so new devices don't power on"],
 ["Transceiver mismatch","Optics of different types or wavelengths on each end"]]},
{obj:"5.2", name:"PoE standards", items:[["802.3af (PoE)","Up to 15.4 W per port"],["802.3at (PoE+)","Up to 30 W per port"],["802.3bt (PoE++)","Up to 60 W (Type 3) or 90 W (Type 4) per port"]]},
{obj:"5.3", name:"Network service issues", items:[
 ["Switching loop","Redundant links without STP cause broadcast storms and MAC table flapping"],
 ["Incorrect VLAN assignment","Port in the wrong VLAN, so the host can't reach its gateway or peers"],
 ["Address pool exhaustion","DHCP scope out of addresses, so new clients get APIPA"],
 ["Incorrect default gateway","Host can reach its own subnet but nothing beyond it"],
 ["Duplicate IP address","Two hosts with the same address cause intermittent connectivity and conflict warnings"],
 ["Incorrect subnet mask","Host misjudges which addresses are local, breaking some destinations"],
 ["Missing default route","Router can reach its connected networks but not the internet"]]},
{obj:"5.4", name:"Performance issues", items:[
 ["Latency","Delay for a packet to travel from source to destination"],
 ["Jitter","Variation in latency between packets, harmful to voice and video"],
 ["Packet loss","Packets that never arrive, often from congestion or errors"],
 ["Bottleneck","The slowest link or device limiting overall throughput"],
 ["Bandwidth","Maximum theoretical capacity of a link"],["Throughput","Actual data rate achieved"],
 ["Congestion","More traffic than a link or device can handle"],
 ["Channel overlap","Nearby APs on overlapping frequencies degrade each other"],
 ["Client disassociation","Clients repeatedly dropped from an AP, from interference, roaming or attacks"],
 ["Roaming misconfiguration","APs with mismatched SSIDs or security, or poor overlap, break handoffs"]]},
{obj:"5.5", name:"Tools", items:[
 ["ping","Tests reachability and round-trip time with ICMP echo"],["traceroute / tracert","Lists each router hop to a destination"],
 ["nslookup","Queries DNS servers interactively, on Windows and Linux"],["dig","Detailed DNS query tool common on Linux"],
 ["tcpdump","Command-line packet capture"],["netstat","Shows connections and listening ports"],["ipconfig / ip / ifconfig","Shows and manages interface addressing"],
 ["arp","Shows or edits the IP-to-MAC cache"],["Nmap","Scans hosts for open ports and services"],["LLDP / CDP","Neighbor discovery protocols showing what is connected to each port"],
 ["Protocol analyzer","Captures and decodes packets in detail, such as Wireshark"],["Speed tester","Measures actual throughput to a test server"],
 ["Toner and probe","Traces an unlabeled cable to its other end"],["Cable tester","Verifies wire map, continuity and shorts"],["Tap","Hardware device that copies traffic from a link for monitoring"],
 ["Wi-Fi analyzer","Shows nearby networks, channels and signal strength"],["Visual fault locator","Shines visible light into fiber to find breaks"],["Optical power meter","Measures light level on a fiber in dBm"]]},
{obj:"5.5", name:"Device commands", items:[
 ["show mac address-table","Lists learned MAC addresses with their VLANs and ports"],["show ip route","Displays the routing table"],["show interfaces","Shows status, errors and counters for interfaces"],
 ["show running-config","Displays the active configuration"],["show arp","Lists IP-to-MAC mappings on a router or Layer 3 switch"],["show vlan","Lists VLANs and their access ports"],
 ["show power inline","Shows PoE budget and per-port power"],["show spanning-tree","Shows the root bridge and each port's STP role and state"]]}
];
const PORTS_TABLE = [["FTP","20/21","TCP"],["SFTP","22","TCP"],["SSH","22","TCP"],["Telnet","23","TCP"],["SMTP","25","TCP"],["DNS","53","TCP and UDP"],["DHCP","67/68","UDP"],["TFTP","69","UDP"],["HTTP","80","TCP"],["NTP","123","UDP"],["SNMP","161/162","UDP"],["LDAP","389","TCP"],["HTTPS","443","TCP"],["SMB","445","TCP"],["Syslog","514","UDP"],["SMTPS","587","TCP"],["LDAPS","636","TCP"],["SQL Server","1433","TCP"],["RDP","3389","TCP"],["SIP","5060/5061","TCP and UDP"]];
const ACRONYMS = [["ACL","Access control list"],["APIPA","Automatic Private IP Addressing"],["ARP","Address Resolution Protocol"],["BGP","Border Gateway Protocol"],["BSSID","Basic service set identifier"],["CAM","Content-addressable memory"],["CIDR","Classless Inter-Domain Routing"],["CRC","Cyclic redundancy check"],["DAI","Dynamic ARP Inspection"],["DHCP","Dynamic Host Configuration Protocol"],["DNSSEC","Domain Name System Security Extensions"],["EIGRP","Enhanced Interior Gateway Routing Protocol"],["ESP","Encapsulating Security Payload"],["FHRP","First Hop Redundancy Protocol"],["GRE","Generic Routing Encapsulation"],["IaC","Infrastructure as code"],["IDF","Intermediate distribution frame"],["IKE","Internet Key Exchange"],["IPAM","IP address management"],["LACP","Link Aggregation Control Protocol"],["LLDP","Link Layer Discovery Protocol"],["MDF","Main distribution frame"],["MDIX","Medium dependent interface crossover"],["MIB","Management information base"],["MTBF","Mean time between failures"],["MTTR","Mean time to repair"],["MTU","Maximum transmission unit"],["NAC","Network access control"],["NFV","Network functions virtualization"],["NTS","Network Time Security"],["OSPF","Open Shortest Path First"],["PAT","Port address translation"],["PDU","Power distribution unit (or protocol data unit)"],["PoE","Power over Ethernet"],["PTP","Precision Time Protocol"],["QSFP","Quad small form-factor pluggable"],["RADIUS","Remote Authentication Dial-In User Service"],["RPO","Recovery point objective"],["RSTP","Rapid Spanning Tree Protocol"],["RTO","Recovery time objective"],["SAML","Security Assertion Markup Language"],["SASE","Secure access service edge"],["SD-WAN","Software-defined wide area network"],["SFP","Small form-factor pluggable"],["SIEM","Security information and event management"],["SLA","Service-level agreement"],["SLAAC","Stateless address autoconfiguration"],["SNMP","Simple Network Management Protocol"],["SSE","Security service edge"],["SVI","Switch virtual interface"],["TACACS+","Terminal Access Controller Access-Control System Plus"],["UPS","Uninterruptible power supply"],["VIP","Virtual IP"],["VLSM","Variable-length subnet mask"],["VPC","Virtual private cloud"],["VXLAN","Virtual Extensible LAN"],["WPA","Wi-Fi Protected Access"],["ZTA","Zero trust architecture"]];
